### PR TITLE
Update Standards for Easier Usage

### PR DESCRIPTION
**Pull request by ChrisWiegman**
This allows the standards to be used as a regular composer package in the same manner as the base WordPress Coding Standards. It also includes instructions for doing  so (see the readme) until this can be added to packagist.

Note I made a few assumptions here and cleaned out old code as appropriate. Please advice on any required changes.

### CODE REVIEW

**Comment by ChrisWiegman** [comment]
Tagging @anthonyburchell and @cdils on this as I do not have permissions to open the PR on the primary repo.

**Review by cdils — DISMISSED** [review]
Oh hey! I remember these. Looks good @ChrisWiegman.

**Review by anthonyburchell — APPROVED** [review]
Wow, dang what a surprise! Thanks so much @ChrisWiegman this looks perfect and I think we can finally start getting this into everyones workflow!

**Review by anthonyburchell — CHANGES_REQUESTED** [review]
I think the Makefile structure should be preserved so we can maintain usage in our Solution Center Tech review processes. We often download files from partners and run the global commands against the root dir. We also share this repo with partners to run the code easily to get faster feedback on if their code will pass our requirements.

**Comment by ChrisWiegman** [comment]
@anthonyburchell All scripts should be working. Let me know what you think.

Note I fixed the make file (instead of supression run `make -s install` to suppress output) and, now, the wpecs script should work as described in its help file. Let me know if you have any issues with it.

**Review by anthonyburchell — APPROVED** [review]
Epic. Thank you Chris! Have this checked out in my local and all works as it did before as well as the new changes. 👍 you rock.

**Pull request merged**
